[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests; default-src 'none' data: nickwasused.netlify.app https://*.cloudfront.net; script-src 'self' 'strict-dynamic'; style-src 'self' 'inline'; frame-ancestors 'self'; base-uri 'none'; form-action 'none'; img-src 'self'; font-src 'self'; sandbox ;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
	X-Xss-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
	Expect-CT = "enforce, max-age=30"
    Feature-Policy = "microphone 'none'; geolocation 'none'"
	Accept-Charset = "utf-8"
	Server = ""
	Alt-Svc = 'h2=":443", h2="nickwasused.netlify.app:443"'
	
[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"
