[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' wss://snowflake.freehaven.net https://snowflake-broker.freehaven.net/proxy; script-src 'self' 'unsafe-inline' https://ajax.cloudflare.com https://static.cloudflareinsights.com https://cdn.jsdelivr.net/gh/nickwasused/"
